### ISSUE TITLE
tty is assumed when it might be prompted

### ISSUE THREAD

**Issue by Arnaudv6** [geier/choose#1]
Hello Christian, thanks for this script : it is comes handy indeed !
I actually can not use "choose" as I would, for when I select a line, it gets printed, but not piped.

I am not a shell guru, but I would say my console uses /dev/pts/1 as tty
not /dev/tty which is hardcoded at the end of your script :
any chance used tty can be detected and used in your script ?

Thanks, Arnaudv6

**Comment by geier** [comment]
Sorry, I somehow forgot about this.
`/dev/tty` should always point the the terminal you are currently using. This was just a stupid bug. Should be fixed now, but if it doesn't work for you, please reopen.

**Comment by Arnaudv6** [comment]
It works well indeed : thanks Christian, I enjoy your script very much !
