### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by bfontaine** [geier/choose#2]
Hello,
Could you please tag a release here so we could use it to have `choose` in Homebrew core?
Thanks!

**Comment by geier** [comment]
[Tagged 0.1](https://github.com/geier/choose/releases/tag/v0.1.0) and thank you for making a recipe (if that is the write term in homebrew)!

**Comment by bfontaine** [comment]
Thanks a lot! That’s called a formula, actually :wink:
